sudo: required
services:
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true docker-react npm run test
depoly:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-905418194203"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
